### ISSUE TITLE
A user is able to set specific repetitions (i.e. repeat 4.5days only)

### ISSUE THREAD

**Issue by qiujunbin** [cs2103jan2015-F10-1C/main#19]

**Comment by nevet** [comment]
so you are supporting floating days? So can I put something like 4.3 days since float support all real number? Can I put something like pi days since float support irrational number?

**Comment by isaackhoo** [comment]
ideally, yes. but for now we will try to work with only whole and half days.

**Comment by qiujunbin** [comment]
This is a bonus function - we will keep it for future milestone

**Comment by isaackhoo** [comment]
not going to implement
