### ISSUE TITLE
Changes big functions(add, delete etc) to different classes use inheritance.

### ISSUE THREAD

**Issue by ghost** [cs2103jan2015-F10-1C/main#30]

**Comment by nevet** [comment]
hold on hold on guys, i'm now writing a demo project to demo an OO design. Could you wait for a while for me to finish it, so that we could sync the understanding of the OO design ?

**Comment by ghost** [comment]
Hi Huangda,

Thanks for your reply ;-) We will only do the class after V0.1. The issue I
posted is just for milestone V0.2, only used to ensure that we need to
finish it in the later version of the program. Don't worry ;-) We will make
the program work first.

Thank you!

Regards,
Ruyan

2015-03-06 22:13 GMT+08:00 Huang Da notifications@github.com:

**Comment by ghost** [comment]
Same as issue 41.
