### ISSUE TITLE
The requirements for flexi-command

### ISSUE THREAD

**Issue by nevet** [cs2103jan2015-F10-1C/main#40]
Damith just broadcast an email about what level should flexi-command be, please check if this matches your implementation :)

> All teams should avoid extremely rigid formats such as these:
> *all parameters have to be entered even if they are not relevant to the task
> *parameters should always follow a certain order,
> *date, month, day etc should be entered as separate parameters
> *unnatural formats such as ddmmyyyy (without any separators)
> Those who choose flexi-command have to do much more, moving the command format toward more variety and more natural formats.

**Comment by nevet** [comment]
If you want to try Natural Language Processing (NLP), you could try to find some C++ NLP library online instead of writing your own one.

**Comment by qiujunbin** [comment]
Hi Huang Da, 
allow me to give you some examples and then do advice us your on whether it is flexicommand or not.
For example i want to add task to do homework on the 3 march at 9pm with high priority:

These are the possible inputs that i can do to add the task into the program:
1. add do homework 3 march 9pm -high
2. add do homework on 3 march at 9pm -high
3. add -high 3/3 21:00 do homework
4. add 21:00 do homework on 3 mar -high

These are a few ways to input the task with different position of the task description, time/day/priority. 

Thanks and see you soon.

**Comment by nevet** [comment]
According to Damith's email, I'm afraid we may need to increase the level of flexibility to reach his expectation. But let me clarify with him first before I could tell you some more specific instructions. However, I do think if your program could understand something like `do homework on the 3 march at 9pm with high priority` (i.e. the line you used in your post, it's the most natural "command" right :P ) and process it correctly, everybody will be happy :)

**Comment by isaackhoo** [comment]
Please let us know what kind of flexible command Damith is looking for thanks. But why would u want to type out "priority" when adding a "-" is much simpler and faster?

**Comment by nevet** [comment]
He hasn't replied me on this yet. @isaackhoo it's because saying priority is more natural than typing a '-' :P

**Comment by nevet** [comment]
The key point for flexi-command is to accept as natural input as possible. The ideal (read as ultimate and impossible) goal for this would be something like: by typing "all projects have been done", all project-related items will be marked as done; by typing "important meeting with Damith at 4pm on wed at DR4 COM2" will be recognized as {task: meeting with Damith, time: 18/Mar/2015 Wednesday 4pm, location: DR4 COM2, priority: high}.

**Comment by isaackhoo** [comment]
thats impossible. hahaha! we're switching our bonus feature to GUI!

**Comment by nevet** [comment]
Sure no problem :)
