### ISSUE TITLE
To adopt Object Oriented Programming structure for coding.

### ISSUE THREAD

**Issue by qiujunbin** [cs2103jan2015-F10-1C/main#41]

**Comment by nevet** [comment]
Maybe this one is related to #30 ? (Also notice that you are able to cross referring to some issues using '#' tag in issue tracker :) Try go to issue 30 and see what's changed there)

**Comment by qiujunbin** [comment]
Yups sure. Noted with thanks!

**Comment by isaackhoo** [comment]
completed
