### ISSUE TITLE
[Urgent] Instruction on friday's tutorial

### ISSUE THREAD

**Issue by nevet** [cs2103jan2015-F10-1C/main#59]
Hello guys, sorry for this last minute email. I'm now in New York for some issues, so I will NOT be able to cover the tutorial today (if we have, actually I have no idea how we gonna handle Good Friday). So could you please send your work, i.e. the OODM, to me individually, with graphs and explanations via email? For your V0.3, I will check it later on my own computer.

Sorry for the inconvenience caused and thank you for your cooperations!

**Comment by danielting3** [comment]
alright!

**Comment by ghost** [comment]
Noticed.

**Comment by ghost** [comment]
Hi Huangda, are you ale to run the V0.3 version after pulling from github? I guess there is some problem with that version. If you cannot run it, can you tell us? We will send you the correct one.

**Comment by ghost** [comment]
Hi huangda, the error is fixed!

**Comment by nevet** [comment]
Hi @TingJunYang and @isaackhoo, I haven't received your individual submission by now, could you double check if you sent your submission to the correct email address? The deadline is tonight, 2359. If no response by that moment, I will mark your submission as null :S

**Comment by nevet** [comment]
Sorry @TingJunYang and @isaackhoo, i've found your submission on IVLE, don't bother sending it again :P
